# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/mui-toolpad/v0.1.54/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  alias:
    - swkHUvh
  title: Default page
  content:
    - component: PageRow
      name: pageRow
      props:
        justifyContent: start
      children:
        - component: PageColumn
          name: pageColumn
          layout:
            columnSize: 1.1699163495332086
          children:
            - component: DataGrid
              name: dataGridTache
              layout:
                columnSize: 1
                height: 340
              props:
                rows:
                  $$jsExpression:
                    "affiche.checked === undefined ? listeTache.data.Taches :
                    listeTacheComplete.data.Taches"
                rowsSource: prop
                columns:
                  - field: id
                    type: number
                  - field: utilisateur_id
                    type: number
                  - field: titre
                    type: string
                    width: 148
                  - field: description
                    type: string
                  - field: date_debut
                    type: dateTime
                  - field: date_echeance
                    type: dateTime
                  - field: complete
                    type: boolean
                density: compact
                loading:
                  $$jsExpression:
                    listeTache.isFetching || listeTache.isLoading ||
                    listeTacheComplete.isFetching ||
                    listeTacheComplete.isLoading
            - component: PageRow
              name: pageRow1
              props:
                justifyContent: start
              children:
                - component: Checkbox
                  name: affiche
                  props:
                    mode: switch
                    label: Afficher tâches terminée
                - component: Button
                  name: button
                  props:
                    content: Supprimer Tache
                    size: medium
                    onClick:
                      $$jsExpressionAction:
                        supprimerTache.call(); listeTache.refetch();
                        listeTacheComplete.refetch()
                    disabled:
                      $$jsExpression: dataGridTache.selection === undefined
                - component: Button
                  name: button2
                  props:
                    content: Changer le statut
                    size: medium
                    onClick:
                      $$jsExpressionAction:
                        completeTache.call(); listeTache.refetch();
                        listeTacheComplete.refetch();
                    disabled:
                      $$jsExpression: dataGridTache.selection === undefined
        - component: PageColumn
          name: pageColumn1
          layout:
            columnSize: 0.8300836504667914
          children:
            - component: DataGrid
              name: dataGridSousTache
              layout:
                columnSize: 1
                height: 336
              props:
                rows:
                  $$jsExpression: "listeSousTache.data ? listeSousTache.data.SousTaches : [0]"
                columns:
                  - field: id
                    type: number
                  - field: tache_id
                    type: number
                  - field: titre
                    type: string
                    width: 126
                  - field: complete
                    type: boolean
                loading:
                  $$jsExpression: listeSousTache.isFetching || listeSousTache.isLoading
            - component: PageRow
              name: pageRow2
              props:
                justifyContent: start
              children:
                - component: Button
                  name: button1
                  props:
                    content: Supprimer Sous-Tache
                    fullWidth: false
                    color: secondary
                    disabled:
                      $$jsExpression: dataGridSousTache.selection === undefined
                    onClick:
                      $$jsExpressionAction: supprimerSousTache.call(); listeSousTache.refetch()
                - component: Button
                  name: button3
                  props:
                    content: Changer le statut
                    color: secondary
                    disabled:
                      $$jsExpression: dataGridSousTache.selection === undefined
                    onClick:
                      $$jsExpressionAction: completeSousTache.call(); listeSousTache.refetch()
    - component: PageRow
      name: pageRow3
      props:
        justifyContent: start
      children:
        - component: PageColumn
          name: pageColumn2
          layout:
            columnSize: 1
          children:
            - component: Text
              name: text
              layout:
                columnSize: 1
              props:
                value: Modifier une tâche
            - component: Form
              name: form
              props:
                submitButtonText: Modifier
                onSubmit:
                  $$jsExpressionAction:
                    modifierTache.call(); listeTache.refetch();
                    listeTacheComplete.refetch();
              children:
                - component: PageRow
                  name: pageRow4
                  props:
                    justifyContent: start
                  children:
                    - component: Text
                      name: text4
                      layout:
                        columnSize: 0.6546961050003597
                      props:
                        value: titre
                    - component: TextField
                      name: titreTacheM
                      layout:
                        columnSize: 1.3453038949996403
                      props:
                        fullWidth: true
                        isRequired: true
                        defaultValue:
                          $$jsExpression: dataGridTache.selection.titre
                - component: PageRow
                  name: pageRow5
                  props:
                    justifyContent: start
                  children:
                    - component: Text
                      name: text5
                      layout:
                        columnSize: 0.6546961050003597
                      props:
                        value: description
                    - component: TextField
                      name: descriptionTacheM
                      layout:
                        columnSize: 1.3453038949996403
                      props:
                        fullWidth: true
                        isRequired: true
                        defaultValue:
                          $$jsExpression: dataGridTache.selection.description
                - component: PageRow
                  name: pageRow6
                  props:
                    justifyContent: start
                  children:
                    - component: Text
                      name: text6
                      layout:
                        columnSize: 0.6546961050003597
                      props:
                        value: date de début
                    - component: TextField
                      name: dateDebutTacheM
                      layout:
                        columnSize: 1.3453038949996403
                      props:
                        fullWidth: true
                        isRequired: true
                        defaultValue:
                          $$jsExpression: dataGridTache.selection.date_debut
                - component: PageRow
                  name: pageRow7
                  props:
                    justifyContent: start
                  children:
                    - component: Text
                      name: text34
                      layout:
                        columnSize: 0.6546960624705778
                      props:
                        value: date d'échéance
                    - component: TextField
                      name: dateEcheanceTacheM
                      layout:
                        columnSize: 1.3453039375294222
                      props:
                        fullWidth: true
                        isRequired: true
                        defaultValue:
                          $$jsExpression: dataGridTache.selection.date_echeance
                - component: PageRow
                  name: pageRow16
                  props:
                    justifyContent: start
                  children:
                    - component: Text
                      name: text15
                      props:
                        value: Statut
                    - component: Select
                      name: completeTacheM
                      layout:
                        horizontalAlign: end
                      props:
                        options:
                          - "true"
                          - "false"
                        fullWidth: false
                        defaultValue:
                          $$jsExpression: dataGridTache.selection.complete
                        size: small
        - component: PageColumn
          name: pageColumn3
          layout:
            columnSize: 1
          children:
            - component: Text
              name: text1
              layout:
                columnSize: 1
              props:
                value: Modifier une sous-tâche
            - component: Form
              name: form1
              props:
                submitButtonText: Modifier
                onSubmit:
                  $$jsExpressionAction: modifierSousTache.call(); listeSousTache.refetch()
              children:
                - component: PageRow
                  name: pageRow8
                  props:
                    justifyContent: start
                  children:
                    - component: Text
                      name: text8
                      props:
                        value: titre
                      layout:
                        columnSize: 0.6560773625631022
                    - component: TextField
                      name: titreSousM
                      layout:
                        columnSize: 1.3439226374368978
                      props:
                        fullWidth: true
                        isRequired: true
                        defaultValue:
                          $$jsExpression: dataGridSousTache.selection.titre
                - component: PageRow
                  name: pageRow9
                  props:
                    justifyContent: start
                  children:
                    - component: Text
                      name: text9
                      props:
                        value: tâche id
                      layout:
                        columnSize: 0.6560773625631022
                    - component: TextField
                      name: tacheIdSousM
                      layout:
                        columnSize: 1.3439226374368978
                      props:
                        fullWidth: true
                        isRequired: true
                        placeholder: ""
                        name: ""
                        defaultValue:
                          $$jsExpression: dataGridSousTache.selection.tache_id
                - component: PageRow
                  name: pageRow17
                  props:
                    justifyContent: start
                  children:
                    - component: Text
                      name: text16
                      props:
                        value: Statut
                    - component: Select
                      name: completeSousM
                      layout:
                        horizontalAlign: end
                      props:
                        options:
                          - "true"
                          - "false"
                        defaultValue:
                          $$jsExpression: dataGridSousTache.selection.complete
  queries:
    - name: listeTache
      mode: query
      query:
        kind: rest
        url:
          $$jsExpression:
            "`${parameters.API_HOST}/tachesMemoire/taches/liste/${parameter\
            s.id}`"
        headers:
          [
            { name: Authorization, value: { $$env: API_KEY } },
            { name: Utilisateur, value: { $$env: USER_ID } },
          ]
        method: GET
        searchParams: []
      parameters:
        - name: id
          value: "1"
        - name: API_HOST
          value:
            $$env: API_HOST
    - name: listeSousTache
      mode: query
      query:
        kind: rest
        url:
          $$jsExpression: "`${parameters.API_HOST}/tachesMemoire/taches/${parameters.id}`"
        headers:
          - name: Authorization
            value:
              $$env: API_KEY
          - name: Utilisateur
            value:
              $$env: USER_ID
        method: GET
        searchParams: []
      parameters:
        - name: id
          value:
            $$jsExpression: dataGridTache.selection.id
        - name: API_HOST
          value:
            $$env: API_HOST
    - name: completeTache
      mode: mutation
      query:
        kind: rest
        url:
          $$jsExpression: "`${parameters.API_HOST}/tachesMemoire/taches/${parameters.id}`"
        headers:
          - name: Authorization
            value:
              $$env: API_KEY
          - name: Utilisateur
            value:
              $$env: USER_ID
        method: PATCH
        searchParams: []
      parameters:
        - name: API_HOST
          value:
            $$env: API_HOST
        - name: id
          value:
            $$jsExpression: dataGridTache.selection.id
    - name: completeSousTache
      mode: mutation
      query:
        kind: rest
        url:
          $$jsExpression: "`${parameters.API_HOST}/tachesMemoire/sousTaches/${parameters.id}`"
        headers:
          - name: Authorization
            value:
              $$env: API_KEY
          - name: Utilisateur
            value:
              $$env: USER_ID
        method: PATCH
        searchParams: []
      parameters:
        - name: API_HOST
          value:
            $$env: API_HOST
        - name: id
          value:
            $$jsExpression: dataGridSousTache.selection.id
    - name: supprimerTache
      mode: mutation
      query:
        kind: rest
        url:
          $$jsExpression: "`${parameters.API_HOST}/tachesMemoire/taches/${parameters.id}`"
        headers:
          - name: Authorization
            value:
              $$env: API_KEY
          - name: Utilisateur
            value:
              $$env: USER_ID
        method: DELETE
        searchParams: []
      parameters:
        - name: API_HOST
          value:
            $$env: API_HOST
        - name: id
          value:
            $$jsExpression: dataGridTache.selection.id
    - name: supprimerSousTache
      mode: mutation
      query:
        kind: rest
        url:
          $$jsExpression: "`${parameters.API_HOST}/tachesMemoire/sousTaches/${parameters.id}`"
        headers:
          - name: Authorization
            value:
              $$env: API_KEY
          - name: Utilisateur
            value:
              $$env: USER_ID
        method: DELETE
        searchParams: []
      parameters:
        - name: API_HOST
          value:
            $$env: API_HOST
        - name: id
          value:
            $$jsExpression: dataGridSousTache.selection.id
    - name: listeTacheComplete
      mode: query
      query:
        kind: rest
        url:
          $$jsExpression:
            "`${parameters.API_HOST}/tachesMemoire/taches/listeComplete/${p\
            arameters.id}`"
        searchParams: []
        headers:
          - name: Authorization
            value:
              $$env: API_KEY
          - name: Utilisateur
            value:
              $$env: USER_ID
        method: GET
      parameters:
        - name: id
          value: "1"
        - name: API_HOST
          value:
            $$env: API_HOST
    - name: modifierTache
      mode: mutation
      query:
        kind: rest
        url:
          $$jsExpression: "`${parameters.API_HOST}/tachesMemoire/taches/${parameters.id}`"
        headers:
          - name: Authorization
            value:
              $$env: API_KEY
          - name: Utilisateur
            value:
              $$env: USER_ID
        body:
          kind: raw
          content:
            $$jsExpression: "`{\r

              \  \"titre\" : \"${parameters.titre}\",\r

              \  \"description\" : \"${parameters.description}\",\r

              \  \"date_debut\" : \"${parameters.date_debut}\",\r

              \  \"date_echeance\" : \"${parameters.date_echeance}\",\r

              \  \"complete\" : ${parameters.complete}\r

              \r

              }`"
          contentType: application/json
        method: PUT
        searchParams: []
      parameters:
        - name: API_HOST
          value:
            $$env: API_HOST
        - name: id
          value:
            $$jsExpression: dataGridTache.selection.id
        - name: titre
          value:
            $$jsExpression: titreTacheM.value
        - name: description
          value:
            $$jsExpression: descriptionTacheM.value
        - name: date_debut
          value:
            $$jsExpression: dateDebutTacheM.value
        - name: date_echeance
          value:
            $$jsExpression: dateEcheanceTacheM.value
        - name: complete
          value:
            $$jsExpression: completeTacheM.value
    - name: modifierSousTache
      mode: mutation
      query:
        kind: rest
        url:
          $$jsExpression: "`${parameters.API_HOST}/tachesMemoire/sousTaches/${parameters.id}`"
        headers:
          - name: Authorization
            value:
              $$env: API_KEY
          - name: Utilisateur
            value:
              $$env: USER_ID
        body:
          kind: raw
          content:
            $$jsExpression: "`{\r

              \  \"tache_id\": ${parameters.tache_id},\r

              \  \"titre\" : \"${parameters.titre}\",\r

              \  \"complete\": ${parameters.complete}\r

              }`"
          contentType: application/json
        method: PUT
        searchParams: []
      parameters:
        - name: API_HOST
          value:
            $$env: API_HOST
        - name: id
          value:
            $$jsExpression: dataGridSousTache.selection.id
        - name: titre
          value:
            $$jsExpression: titreSousM.value
        - name: tache_id
          value:
            $$jsExpression: tacheIdSousM.value
        - name: complete
          value:
            $$jsExpression: completeSousM.value
  display: shell
